{{- if $.Values.istio.p2p }}
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name:  bsc1-p2p-endpoint
  namespace: {{ $.Values.namespace }}
spec:
  endpoints: 
  - dnsName:  {{ $.Values.istio.p2p.dns }}
    recordTTL: 180
    recordType: CNAME
    targets:
    - {{ $.Values.istio.target }}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:    
  name: bsc1-p2p-gateway
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: {{ $.Values.istio.ingressgwname }}
    istio: ingressgateway
  servers:
  - hosts:
    - {{ $.Values.istio.p2p.dns }}
    port:
      name: tcp-bsc1-p2p
      number: {{ $.Values.port }}
      protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bsc1-p2p-vsvc
  namespace: {{ $.Values.namespace }}
spec:
  gateways:
  - bsc1-p2p-gateway
  hosts:
  - {{ $.Values.istio.p2p.dns }}
  tcp:
  - match:
    - port: {{ $.Values.port }}
    route:
    - destination:
        host: bsc-node
        port:
          number: {{ $.Values.port }}
{{- end }}
